name: Ardour Cross Compile Build

on:
  push:
    branches: [ x-win ]
  pull_request:
    branches: [ x-win ]
  schedule:
    # “At 18:00 on every day-of-week from Monday through Sunday.”
    - cron: '0 18 * * *'
env:
  # TODO: Change variable to your image's name.
  ARCH: x86_64
  UPLOAD_SERVICE: file.io

jobs:
  ardour-build:
    runs-on: ubuntu-20.04
    container:
      image: vitzy/flameshot:debian-buster
      # options: -v /__w/ardour-build/ardour-build:/home/ardour-build:rw
    steps:

      # - uses: actions/checkout@v2
      #   with:
      #     repository: 'Ardour/ardour'
      #     ref: 'master'
      #     # Relative path under $GITHUB_WORKSPACE (/github/workspace) to place the repository
      #     path: '/ardour'

      # - uses: actions/checkout@v2
      #   with:
      #     ref: 'dev'
          # Relative path under $GITHUB_WORKSPACE (/github/workspace) to place the repository
          # path: '/ardour-build'

      - name: install pre-build dependencies
        run: |
            apt-get update && apt-get install -y --allow-downgrades --allow-remove-essential \
              --allow-change-held-packages python python3 python3-pip python3-wheel python3-setuptools \
              gcc-mingw-w64 g++-mingw-w64 gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 mingw-w64 \
              pkg-config yasm libtool zstd rsync unzip dos2unix curl git wget apt-transport-https \
              gnupg ca-certificates

      - name: patch source code
        run: |
            git clone -b master https://github.com/Ardour/ardour /home/ardour
            git clone -b x-win https://github.com/ZetaoYang/ardour-build /home/ardour-build
            chmod +x /home/ardour-build/ci/*.sh
            chmod +x /home/ardour-build/ci/services/*.sh
            rm -f /home/ardour/tools/x-win/compile.sh
            rm -f /home/ardour/tools/x-win/package.sh
            mv /home/ardour-build/ci/compile.sh /home/ardour/tools/x-win
            mv /home/ardour-build/ci/package.sh /home/ardour/tools/x-win
            dos2unix /home/ardour/tools/x-win/compile.sh
            dos2unix /home/ardour/tools/x-win/package.sh
            dos2unix /home/ardour/tools/define_versions.sh

      - name: install ardour dependencies
        run: |
            bash /home/ardour-build/ci/install.sh

      - name: build ardour 
        run: |
            bash /home/ardour-build/ci/before_build.sh
            bash /home/ardour/tools/x-win/compile.sh

      - name: package ardour 
        run: |
            bash /home/ardour/tools/x-win/package.sh

      - name: upload binary
        run: |
            TEMP_DOWNLOAD_URL=$(sh /home/ardour-build/ci/services/${UPLOAD_SERVICE}.sh /var/tmp/Ardour-*-Setup.exe)
            echo Download URL is $TEMP_DOWNLOAD_URL. 
          
